name: Deploy to GitHub Pages
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}
  workflow_run:
    workflows: ["Update data.json daily"]
    types: [completed]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps (for safety)
        run: npm ci || npm i
      - name: Ensure latest data.json
        run: npm run update || true
      - name: Copy data to public
        run: mkdir -p public/data && cp -f data/data.json public/data/data.json
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
