name: Update data.json daily

on:
  schedule:
    - cron: "0 11 * * *"   # 11:00 UTC = 19:00 北京时间
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: update-data
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci || npm i

      - name: Update feeds
        run: npm run update

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/data.json
          git diff --cached --quiet && echo "No changes" || git commit -m "chore: update data.json [skip ci]"
          git push
